### ISSUE TITLE
Unable to Payback DAI for very first vault - Payback Vault

### ISSUE THREAD

**Issue by AflahSohailZake** [OasisDEX/oasis-borrow#2151]
**Describe the bug**
When the user creates a vault for the very first time through proxy contract. Then if the user try to payback DAI, then it shows wrong Collateral Ratio. And user is unable to payback DAI. Dai debt is not displayed correctly, because of that we cant Payback DAI. 
Let say 0.001 dai is left but our collateral ratio becomes soo high and it appears wrong. 

**To Reproduce**
Steps to Reproduce:

Enter the URL "https://oasis.app/?network=goerli#multiply"
Click on Connect Wallet Button on Navbar.
Click on Metamask & Change the Network to Goerli Testnet.
Sign in with the very new account of Metamask.
Accept the terms & condition.
Click on Borrow APP & select any ETH-C, ETH-A or ETH-B.
Create Proxy Contract.
Confirm & Create Vault.
Click on my position and select the first ever vault you created.
Select the option "Payback DAI"
Enter the Payback DAI & collateral (ETH) value.
You will see the WRONG Collateral RATION appearing under Collateral Ratio heading in Overview.

**Expected behavior**
The user should be able to Payback DAI & gets it collateral back for the very first created vault. 

**Screenshots**
![Oasis APP](https://user-images.githubusercontent.com/81463675/224626205-219e2b0b-d48c-437b-b652-5dc0aaf023af.png)

**Desktop/Smartphone (please complete the following information):**
 - OS: [ MAC, windows & Linux]
 - Browser [chrome]
 - Connection method [Metamask]
 - Version [mac os monterey 12.2, windows 10, Ubuntu 22.04.2]

**Additional context**
Issue appears on TestNet goerli so you have to change network to testnet then follow the steps.

**Comment by marcinciarka** [comment]
When you open the vault you immediately begin to accrue debt. In the example provided the user is attempting to repay certain amount of DAI. But their position will have accrued a tiny amount of debt. So the actual position debt will be something like the amount + 0.000000001 DAI
 
You cannot repay the whole amount of DAI because Maker protocol does not allow you to leave a small amount of debt in a position (dust limits). This is also why the simulated Col ratio is so high, the vault will have a very high collateral value in relation to the tiny amount of debt left in the position.
