### ISSUE TITLE
I cant see DAI generated after opening a n ETH-C vault from my safe.

### ISSUE THREAD

**Issue by AugustoL** [OasisDEX/oasis-borrow#2741]
**Describe the bug**
I submitted a transaction to create a vault on ETH-C using 161 ETH as collateral with the minimum liquidation price possible, when teh transaction was confirmed I didnt recieved any DAI on the safe account, I was expecting to receive 66000 DAI.

**To Reproduce**

 Go to ETH-A and create a vault from a gnosis safe.

**Expected behavior**
I was expecting to recieve 66000 DAI on my safe account but it didnt happened.

**Screenshots**
![Screenshot from 2023-08-18 20-14-40](https://github.com/OasisDEX/oasis-borrow/assets/7763867/fe2aeb92-0e3a-45f2-844e-563a60498294)
![Screenshot from 2023-08-18 20-15-09](https://github.com/OasisDEX/oasis-borrow/assets/7763867/f2256857-c929-4b36-ba08-89675eee4f16)

**Desktop/Smartphone (please complete the following information):**
Linux, Ubuntu.

**Additional context**
I did this plenty of times and I always received dai every time I created a vault, what happened? im freaking out.

Here is the TX of the vault creation: https://etherscan.io/tx/0xd9ca74fc244de849c1a13b46b8d44733f37bf0106b75b20cb628bca5190e8357

**Comment by piekczyk** [comment]
Hello [AugustoL](https://github.com/AugustoL). You've opened ETH-C multiply position which means that all debt that has been generated was used to buy more collateral, in your case 39.9 ETH. That is why Total collateral in your position is 200.9 ETH instead of 161 ETH. You can check history event of this action too see what exactly happened.

<img width="712" alt="image" src="https://github.com/OasisDEX/oasis-borrow/assets/39706811/cce5745b-7e4f-4969-8c53-e411621bc372">

Keep in mind that you can switch between multiply and borrow vault type using option in form dropdown.

<img width="234" alt="image" src="https://github.com/OasisDEX/oasis-borrow/assets/39706811/f677de51-5b3b-4ac4-8532-486cb30ffefe">

If you will have more question please reply here or reach out to us using our Discord support channel. Regards.

**Comment by AugustoL** [comment]
Perfect, thanks!!, yes I realized a few minutes after creating the issue. I guess thats the difference between ETH-C and ETH B and A? That automatically increases the collateral instead of sending back generated DAI?

What I wanted to do was to use the DAI generated to buy ETH and then sell the ETH back at a higher price and pay back the DAI debt ending up with ETH winnings in the end. I guess this as been done automatically now and all that I need to do is just close out the vault when ETH is at a higher price?

**Comment by piekczyk** [comment]
No, the differences between ilks ETH-A, ETH-B and ETH-C are things like dust limits and borrow rates. You can open ETH-C position using either our [Borrow](https://summer.fi/borrow) or [Multiply](https://summer.fi/multiply) products built on the top of Maker protocol. I encourage you to read articles in our knowledge base [here](https://docs.summer.fi/products/multiply). 

Answering your second question - yes, you can just wait until ETH price will rise and at selected moment close your position or increase multiply, hoping for even higher increase of ETH price.

Btw. check our Take Profit feature which you can find [here](https://summer.fi/ethereum/maker/30965#optimization). It will realize your strategy automatically when ETH price will hit selected threshold :)

<img width="495" alt="image" src="https://github.com/OasisDEX/oasis-borrow/assets/39706811/e09a1f5f-1072-4ca1-b47b-8e481e8e4126">
